# SPDX-FileCopyrightText: 2026 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Build with Alire

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: AdaCore/Ada_Drivers_Library
        path: adl
    - uses: alire-project/setup-alire@v5
    - name: Build project
      run: |
        alr                build
        alr -C picowi      build
        alr -C enet_picowi build
    - name: Build examples
      run: |
        alr -C examples/blink     build
        alr -C examples/enet_ping build
